### ISSUE TITLE
create new role of user ... bug

### ISSUE THREAD

**Issue by ziyanziyu** [LavaLite/cms#100]
I was creating a new role as well as the user, when the error, the error for the Argument of 1 FormData.constructor does not implement interface HTMLFormElement. 
TypeError:176th lines in admin.js

**Comment by Renfos** [comment]
https://github.com/LavaLite/cms/blob/master/public/js/admin.js#L176

update this line with the below code.

        var formData = new FormData(form.attr('id'));
