### ISSUE TITLE
How can u close the "G-reCAPTCHA" ? 

### ISSUE THREAD

**Issue by 54853315** [LavaLite/cms#101]
Hello!

Here is it ,I Set the key at '.env' file.

 When i try to create a new user , I click the submit button .  it show me this error : 

'The g-recaptcha-response field is not correct.'

How can i close the grecaptcha ?

**Comment by Renfos** [comment]
Register with re-captcha[https://www.google.com/recaptcha]
And give details in .env file  for the below keys.

RECAPTCHA_PUBLIC_KEY=
RECAPTCHA_PRIVATE_KEY=
