### ISSUE TITLE
I have problems Install file .env  --> help me

### ISSUE THREAD

**Issue by iamnanz** [LavaLite/cms#113]
<img width="1008" alt="screen shot 2559-08-17 at 9 35 20 pm" src="https://cloud.githubusercontent.com/assets/9876626/17740517/12e71cde-64c3-11e6-8ac0-608e5a710794.png">

<img width="459" alt="screen shot 2559-08-17 at 9 40 23 pm" src="https://cloud.githubusercontent.com/assets/9876626/17740611/82c72bc0-64c3-11e6-98fb-1155e923a315.png">

i set file .env ?

**Comment by georgemjohn** [comment]
on mac from base folder run 
touch storage/database.sqlite
