### ISSUE TITLE
Class MenuTableSeeder does not exist  

### ISSUE THREAD

**Issue by dolia** [LavaLite/cms#131]
MacBook-Pro:cms dolia$ php artisan migrate --seed
Nothing to migrate.

                                        
  [ReflectionException]                 
  Class MenuTableSeeder does not exist

**Comment by georgemjohn** [comment]
Run the artisan commands to publish migrations and seeds

- php artisan vendor:publish --tag=migrations  
- php artisan vendor:publish --tag=seeds  
- composer dump-autoload

**Comment by acedesigns** [comment]
Hi @georgemjohn 

I think this should be included in the [Documentations](https://lavalite.readme.io/docs), as I cam from Laravel 5.2 and now I am jumping to 5.4.
