### ISSUE TITLE
Some problems with installation

### ISSUE THREAD

**Issue by DiCore** [LavaLite/cms#15]
Hello, I'm trying to install it but i get an error from composer, any suggestions

Created project in C:\xampp\htdocs\lavalite\cms
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for greggilbert/recaptcha dev-master -> satisfiable by greggilbert/recaptcha[dev-master].
    - don't install illuminate/support v5.0.0|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.0-BETA1
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.1
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.10
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.11
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.12
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.13
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.14
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.15
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.16
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.17
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.2
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.3
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.4
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.5
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.6
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.7
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.8
    - don't install illuminate/support v5.0.0|don't install laravel/framework v4.2.9
    - greggilbert/recaptcha dev-master requires illuminate/support 5.0.* -> satisfiable by illuminate/support[5.0.x-dev, v5.0.0].
    - Conclusion: don't install illuminate/support 5.0.x-dev
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[4.2.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by HashmatWaziri** [comment]
step 1: git Bash C:\ProgramData\ComposerSetup\bin . step  2: run  php composer.phar self-update. step 3: git Bash application and , as usual, run composer update.

**Comment by Renfos** [comment]
Try install again
