### ISSUE TITLE
Error Occoured

### ISSUE THREAD

**Issue by commanderinchief** [LavaLite/cms#150]
After Install, I run these command "php artisan migrate --seed". Then msg reply migrate succeed and nothings to migrate. Next I run "php artisan serve" .
After that, I called the site with "localhost:8000" but can't run site. It's return with following error.

FileNotFoundException in compiled.php line 7487: File does not exist at path C:\xampp\htdocs\Lavalite\public\themes/public/config.php

please solve my problem and guide me step by step to run the cms.
Thanks.

**Comment by georgemjohn** [comment]
Please follow these steps

- composer create-project LavaLite/cms --prefer-dist website

- Change to the installed directory

- php artisan lavalite:install --force

**Comment by commanderinchief** [comment]
Thanks @georgemjohn 
Problem is solved by your help.
