### ISSUE TITLE
Problem with creating and viewing blocks

### ISSUE THREAD

**Issue by navneetccna** [LavaLite/cms#210]
When i tried to create new block getting following error

Invalid argument supplied for foreach() (View: \packages\litecms\block\resources\views\admin\block\partial\entry.blade.php) (View:\packages\litecms\block\resources\views\admin\block\partial\entry.blade.php)
\vendor\anahkiasen\former\src\Former\Form\Fields\Select.php#191

**Comment by Renfos** [comment]
Please install new updates
