### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by navneetccna** [LavaLite/cms#211]
git clone git@github.com:LavaLite/cms.git
From a command line open in the folder, run composer install

Warning: Ambiguous class resolution, "Litepie\Package\Repositories\Criteria\ModulePublicCriteria" was found in both "D:/wamp64/www/lavalite/vendor/lavalite/framework/src/Litepie\Message\Repositories\Criteria\MessagePublicCriteria.php" and "D:/wamp64/www/lavalite/vendor/lavalite/framework/src/Litepie\Task\Repositories\Criteria\TaskPublicCriteria.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Litepie\Alerts\AlertsServiceProvider' not found

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by wqj97** [comment]
same issue here

**Comment by Renfos** [comment]
Please install new update.
Or remove Litepie\Alerts\AlertsServiceProvide from `config/app.php`
