### ISSUE TITLE
Error in Admin Dashboard

### ISSUE THREAD

**Issue by rrreza** [LavaLite/cms#212]
When i login in admin, and go to profile, the lavalite say Error:

`"Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: View [admin.auth.edit] not found. (View: C:\www\Re\public\themes\admin\views\user\profile.blade.php) ◀"`

I install a new project but I see this error!

**Comment by Renfos** [comment]
This error is fixed.
Please update the theme using composer.
