### ISSUE TITLE
Is Ecommerce package not maintaing anymore?

### ISSUE THREAD

**Issue by darron1217** [LavaLite/cms#222]
Hello, I'm a laravel developer interested in Modular Laravel Framework.

I found Ecommerce Package at your website, which is awesome.
https://lavalite.org/products.html

But Ecommerce product's `lavalite/framework` composer version is 2.0, while newest version is 3.1.

So... here's my Question & Suggestion

1. Is Ecommerce product still maintaing or planning to do it?
2. How about creating public git repository? (I want to contribute on it)

**Comment by Renfos** [comment]
We are busy wt the update of core CMS package , It will be finished in 1-2 months time
Once it is finished our next plan is to develop other packages, E-commerce package is in our priority list. If you are interested will provide a public repository for updating it.

**Comment by tanvirgaus** [comment]
Any tentative date to get the ecom working?
