### ISSUE TITLE
Install errors and workaround

### ISSUE THREAD

**Issue by appkr** [LavaLite/cms#23]
1. There was bunch of errors in the process of `db:seed`. That was caused by discrepancy between what migration says and what seeder says. The migration forces NOT NULL, but seeder was trying to insert fields with NULL. To remedy this:
  - Need to append `->nullable();` at some schema declaration. http://laravel.io/bin/vBYRk
  - In some cases, need to delete seeder line. e.g. `'key' => NULL`. http://laravel.io/bin/yGLRL

2. I had to rewrite path declaration not to include `/` in `public/themes/admin/config.php` and `public/themes/public/config.php`. 
e.g. `$theme->asset()->add('jquery', '/vendor/...');` to `$theme->asset()->add('jquery', 'vendor/...');`

3. I had to remove `jQuery.appear()` function call in `public/themes/public/assets/js/scripts.js`.
```
jQuery(this).appear(function() {
    jQuery(this).delay(350).animate({opacity:1,right:"0px"},1000);
});
```

to 

```
// jQuery(this).appear(function() {
    jQuery(this).delay(350).animate({opacity:1,right:"0px"},1000);
// });
```

**Comment by Renfos** [comment]
New version updated
