### ISSUE TITLE
Ver 5.5 Install success. Can't log in admin page.

### ISSUE THREAD

**Issue by icekingcy** [LavaLite/cms#234]
Install success under artisan.
When i open http://localhost/admin/login .I can see the login page. I input username and password ,then click login, just refresh the page. I can't log in. I can confirm my username and password are right. I have remove everything(code,database ..) and reinstall many times.   Same problem.

And nothing under log folder.

**Comment by Renfos** [comment]
Issues fixed with the installer.
Run
```
composer update
php artisan lavalite:install
```
