### ISSUE TITLE
how to insert image to page content

### ISSUE THREAD

**Issue by acecx** [LavaLite/cms#235]
we can upload images,but images can't insert in to content autocomplete

The images saved storage/uploads/...  it's not storage/app/public/

And when uploaded the image can't view,the url was err.

**Comment by KuNman** [comment]
Same problem.

**Comment by Renfos** [comment]
The url root should be pointed to the public folder. If you have multiple application is there in your local server assign a port for this website. Eg: `http://localhost:83`  This will solve the issue.
