### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by chiranjitkuiry** [LavaLite/cms#238]
NO matter what I do in the admin panel(e.g edit page ) it always says " internal server error ."

And where is the table, I Downloaded lavalite e-commerce product and did all the instructions stuff. Every thinks fine except Above mention error when it comes to the admin section. Later I realized that there only two table in my DB. Can anyone give some solution

**Comment by Renfos** [comment]
Look in the database folder for sql file.

**Comment by chiranjitkuiry** [comment]
I dont have sql file. what to do to get the sql file

**Comment by viterzbayraku** [comment]
Same problem

**Comment by georgemjohn** [comment]
Run the below php artisan command
`php artisan lavalite:install`
It will migrate the tables to your database.
Or run 
`php artisan migrate:refresh --seed`
to migrate and seed your database.
