### ISSUE TITLE
Trait 'Litepie\http\Traits\View' not found

### ISSUE THREAD

**Issue by chandrawira** [LavaLite/cms#242]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Trait 'Litepie\http\Traits\View' not found

**Comment by KuNman** [comment]
Please describe your issue more precisely. Where do you get this error?
Try run `composer install` and `composer dumpautoload`.

**Comment by chandrawira** [comment]
Fresh install from composer...

Fix! with composer dumpautoload.
