### ISSUE TITLE
Problem with initial installation.

### ISSUE THREAD

**Issue by Mattz0r** [LavaLite/cms#243]
I am following the installation guide at: https://lavalite.org/docs/master/installation

When I run the command: php artisan lavalite:install

After it gets to the artisan migration part, I am presented with the following error:

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `password_resets` add index `password_resets_email_index`(`email`))

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      /data/[redacted]/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

  2   PDOStatement::execute()
      /data/[redacted]blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

Please advise how to resolve.

**Comment by gachowy** [comment]
One of the popular issues for Laravel with older versions of MySQL.
Look on that, I hope it can solve that:
https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by Mattz0r** [comment]
Thanks - I am using MariaDB, not an older MySQL version, I hadn't come across this as I am new to Laravel.

**Comment by KuNman** [comment]
Maybe try install it on MySQL first to verify does it is problem with DB version or p.ex. your server config.

**Comment by nicckk3** [comment]
First of you need to add one line in to app\Providers\AppServiceProvider.php 
 Schema::defaultStringLength(191); in boot() function. them try again..
