### ISSUE TITLE
Own Template include

### ISSUE THREAD

**Issue by Harry055** [LavaLite/cms#245]
Hi,
i want include own landing page show 
![landingpage](https://user-images.githubusercontent.com/35743325/39084671-5a3fe712-4579-11e8-8a08-7f50b20154f4.PNG)

where I do that?

and it work that Project One view add in an loop for first Project and after some time show nest Project  etc. ![portfolio](https://user-images.githubusercontent.com/35743325/39084857-707cb990-457b-11e8-9f03-25f85f520bf5.PNG)

or better i want include the [site](https://blackrockdigital.github.io/startbootstrap-modern-business/index.html)

or how i can start it i think the Documentation is scanty

Please help it is important

thx ahead

**Comment by KuNman** [comment]
If you published views in installer (it asks for it) your home page templates are there : [https://i.gyazo.com/d9291238c52b3ffc5281686b03eb7165.png](url) (as Debugbar for Laravel says).

> or better i want include the site

It's not such easy like copy&paste. This is CMS, good for building webpages from scratch. Check pages/blocks if you want build some simple landing-like page.

**Comment by Harry055** [comment]
@KuNman ok i install lavalite right this

1.  `composer create-project LavaLite/cms --prefer-dist website` 
2. `php artisan lavalite:install`

my public web site shows so 
![public](https://user-images.githubusercontent.com/35743325/39087513-77213286-45a2-11e8-85cc-18d32d437225.PNG)

my admin shows so 
![admin](https://user-images.githubusercontent.com/35743325/39087521-8e8cad56-45a2-11e8-96c2-945a8c92395c.PNG)

it is fresh installed what is next step ??

**Comment by KuNman** [comment]
Depends how much time you want to spend on writing page and do you need such powerfull CMS. If not, maybe try Wordpress...
If you want to stay with Lavalite try install Debugbar from Barry (remove social in debugbar config), then you will see which views are currently displayed on screen, so you will have easy access to them. Next, remove unused packages like messages, calendar, tasks...Everything what you don't need. Finally you can starting playing with pages and blocks to customise your content. Be prepared for mindblows and bugs.
