### ISSUE TITLE
PostgreSQL / SQLite support.

### ISSUE THREAD

**Issue by valle6** [LavaLite/cms#25]
Do you intend to offer support to PostgreSQL? For me, PostgreSQL usage is essential.  I think if Eloquent allows different databases, let the developers choose the one that suits them.

**Comment by Renfos** [comment]
New version updated. Please check with PostgreSQL

**Comment by kirchaj** [comment]
I am trying to install on Postgres and have run into this error when running 

php artisan db:seed --class=RoleTableSeeder

[Illuminate\Database\QueryException]                                                    
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "roles" does not exist             
LINE 1: insert into "roles" ("id", "name") values ($1, $2), ($3, $4)...                 
                    ^ (SQL: insert into "roles" ("id", "name") values (1, superuser), (2
                                                                                                                                                               
[PDOException]                                                                          
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "roles" does not exist             
LINE 1: insert into "roles" ("id", "name") values ($1, $2), ($3, $4)...
