### ISSUE TITLE
Instalation errors

### ISSUE THREAD

**Issue by Mtab7** [LavaLite/cms#26]
I'm getting the following errors when I run: sudo composer.phar create-project LavaLite/cms path 2.2.1
Installing lavalite/cms (2.2.1)
  - Installing lavalite/cms (2.2.1)
    Downloading: 100%         

Created project in path
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing psr/log (dev-master 9e45edc)
    Loading from cache

  - Installing loic-sharma/profiler (v1.1.2)
    Loading from cache

  - Installing symfony/translation (2.5.x-dev 165b534)
    Loading from cache

  - Installing symfony/security-core (2.5.x-dev 3a27d7b)
    Loading from cache

  - Installing symfony/routing (2.5.x-dev 46142c3)
    Loading from cache

  - Installing symfony/process (2.5.x-dev 00a1308)
    Loading from cache

  - Installing symfony/debug (2.5.x-dev ed30195)
    Loading from cache

  - Installing symfony/http-foundation (2.5.x-dev 08e7838)
    Loading from cache

  - Installing symfony/event-dispatcher (2.8.x-dev d91fb72)
    Loading from cache

  - Installing symfony/http-kernel (2.5.x-dev 3165238)
    Loading from cache

  - Installing symfony/finder (2.5.x-dev e527ebf)
    Loading from cache

  - Installing symfony/dom-crawler (2.5.x-dev 3860edc)
    Loading from cache

  - Installing symfony/css-selector (2.5.x-dev d45b306)
    Loading from cache

  - Installing symfony/console (2.5.x-dev a43e750)
    Loading from cache

  - Installing symfony/browser-kit (2.5.x-dev b2b78b8)
    Loading from cache

  - Installing swiftmailer/swiftmailer (5.x-dev 21b7eb3)
    Loading from cache

  - Installing stack/builder (dev-master 14afc80)
    Loading from cache

  - Installing predis/predis (0.8.x-dev 4123fcd)
    Loading from cache

  - Installing phpseclib/phpseclib (0.3.10)
    Loading from cache

  - Installing nesbot/carbon (1.17.0)
    Loading from cache

  - Installing monolog/monolog (dev-master 3f1ac65)
    Loading from cache

  - Installing nikic/php-parser (0.9.x-dev ef70767)
    Loading from cache

  - Installing jeremeamia/superclosure (1.0.x-dev 4d89ca7)
    Loading from cache

  - Installing filp/whoops (1.1.6)
    Loading from cache

  - Installing ircmaxell/password-compat (1.0.x-dev 9b99377)
    Loading from cache

  - Installing d11wtq/boris (v1.0.8)
    Loading from cache

  - Installing symfony/filesystem (2.8.x-dev d105506)
    Loading from cache

  - Installing classpreloader/classpreloader (1.0.2)
    Loading from cache

  - Installing patchwork/utf8 (dev-master 47056e3)
    Loading from cache

  - Installing laravel/framework (4.2.x-dev deade43)
    Loading from cache

  - Installing lavalite/user (2.2.0)
    Loading from cache

  - Installing lavalite/page (2.2.0)
    Loading from cache

  - Installing lavalite/contact (2.2.0)
    Loading from cache

  - Installing lavalite/menu (2.2.0)
    Loading from cache

  - Installing lavalite/filer (2.2.0)
    Loading from cache

  - Installing cartalyst/sentry (2.1.x-dev 7dd63df)
    Downloading: 100%         

  - Installing anahkiasen/html-object (1.4.2)
    Loading from cache

  - Installing anahkiasen/former (dev-master d1c3239)
    Loading from cache

  - Installing twig/twig (v1.16.2)
    Loading from cache

  - Installing teepluss/theme (1.2.2)
    Loading from cache

  - Installing intervention/image (dev-master 1009557)
    Loading from cache

  - Installing intervention/imagecache (2.1.2)
    Downloading: 100%         

  - Installing mcamara/laravel-localization (0.14.9)
    Loading from cache

  - Installing dimsav/laravel-translatable (v4.2.1)
    Loading from cache

  - Installing greggilbert/recaptcha (1.1.5)
    Loading from cache

  - Installing lavalite/image (2.2.1.x-dev 004ae6a)
    Loading from cache

symfony/translation suggests installing symfony/config ()
symfony/translation suggests installing symfony/yaml ()
symfony/security-core suggests installing symfony/validator (For using the user password constraint)
symfony/security-core suggests installing symfony/expression-language (For using the expression voter)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/yaml (For using the YAML loader)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
phpseclib/phpseclib suggests installing pear-pear/PHP_Compat (Install PHP_Compat to get phpseclib working on PHP < 4.3.3.)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
d11wtq/boris suggests installing ext-readline (*)
patchwork/utf8 suggests installing ext-wfio (Use WFIO for UTF-8 filesystem access on Windows)
laravel/framework suggests installing doctrine/dbal (Allow renaming columns and dropping SQLite columns.)
cartalyst/sentry suggests installing happydemon/txt (Required Text helpers when using the Kohana implementation)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)

Does anyone know what I'm doing wrong?

**Comment by Renfos** [comment]
New version released please update
