### ISSUE TITLE
Class 'Litecms\Page\Facades' not found

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [LavaLite/cms#265]
Hello,

Installation worked fine, frontend works fine, but on the admin dashboard I get:

`Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Class 'Litecms\Page\Facades' not found (View: /.../lavalitecms/public/themes/admin/views/home.blade.php)"`

Some admin pages work fine though.

Any idea on how to fix this please ?

**Comment by lsteamgeo** [comment]
Hello,
You've to install : 
`composer require litecms/page`
Best regards.

**Comment by ShapesGraphicStudio** [comment]
That did the trick indeed, thank you!

```
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: lavalite/framework
Discovered Package: litecms/block
Discovered Package: litecms/contact
Discovered Package: litecms/page
Discovered Package: mpociot/teamwork
Discovered Package: nesbot/carbon
```

Does that mean I should install all of those too ?

**Comment by georgemjohn** [comment]
Run  `composer update` again to install it properly.

**Comment by georgemjohn** [comment]
Issue solved
