### ISSUE TITLE
array_flip() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by Sohail-Ansari** [LavaLite/cms#295]
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In LaravelLocalization.php line 446:

  array_flip() expects parameter 1 to be array, null given

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by malikghanim** [comment]
I replace the code on 
vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/LaravelLocalization.php
on line number 446 
public function getInversedLocaleFromMapping($locale)
    {
        return \array_flip($this->getLocalesMapping())[$locale] ?? $locale;
    }

replace it by this and it well work perfectly
public function getInversedLocaleFromMapping($locale)
    {
        try {
            return \array_flip($this->getLocalesMapping())[$locale] ?? $locale;
        } catch (\Exception $e) {
            return null;
        }
    }

**Comment by Sohail-Ansari** [comment]
I have also worked for me when I installed the Mcamara/LaravelLocalization manually. It seems like the package has some configuration issue with the current version of Laravel. 

Instantly it manually has worked for me.

**Comment by warifp** [comment]
> public function getInversedLocaleFromMapping($locale)
> {
> try {
> return \array_flip($this->getLocalesMapping())[$locale] ?? $locale;
> } catch (\Exception $e) {
> return null;
> }
> }

Thanks!
