### ISSUE TITLE
Auth guard [.web] is not defined.

### ISSUE THREAD

**Issue by Arkango** [LavaLite/cms#309]
I installed lavalite/news package
and published all file 
[this guide](https://lavalite.org/docs/master/news)

From admin dashboard clicking news tab i have the error 
Auth guard [.web] is not defined.

**Comment by ankitchauhan22** [comment]
Hi,

I'm facing the same issue, not able find any resolution so far. 
any help will be highly appreciated.

I'm ussing
Laravel V 6.12
PHP 7.3

Regards
Ankit Chauhan

**Comment by pouyakondori** [comment]
same problem here. Both in localhost and on the server I have this problem.

**Comment by Arkango** [comment]
https://lavalite.org/discussion/auth-guard-web-is-not-defined

look a this answer
Hi, I had the problem when add blog package. I changed the the code in packages/litecms/blog/routes/web.php " set_route_guard('web').'/blog' to '{guard}/blog' " Now it's working fine. I don't know is this is final solution. Sorry for my bad English

**Comment by mostadev** [comment]
> https://lavalite.org/discussion/auth-guard-web-is-not-defined
> 
> look a this answer
> Hi, I had the problem when add blog package. I changed the the code in packages/litecms/blog/routes/web.php " set_route_guard('web').'/blog' to '{guard}/blog' " Now it's working fine. I don't know is this is final solution. Sorry for my bad English

i already applied this solution but doesn't work after some little search i found that 

`request()->guard();`
located in 
`RouteAndGuard::setGuard(); // line 85`
returns NULL so the result of guard and sub is ".web"
