### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by kirchaj** [LavaLite/cms#32]
I am trying to install on Postgres and have run into this error when running

php artisan db:seed --class=RoleTableSeeder

[Illuminate\Database\QueryException]

SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "roles" does not exist

LINE 1: insert into "roles" ("id", "name") values ($1, $2), ($3, $4)...

^ (SQL: insert into "roles" ("id", "name") values (1, superuser), (2

[PDOException]

SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "roles" does not exist

LINE 1: insert into "roles" ("id", "name") values ($1, $2), ($3, $4)...

**Comment by Renfos** [comment]
Migration files updated
Update user package and try again
