### ISSUE TITLE
Problem with migrations

### ISSUE THREAD

**Issue by budhead** [LavaLite/cms#34]
php artisan db:seed --class=RoleTableSeeder
php artisan db:seed --class=PermissionTableSeeder
php artisan db:seed --class=UserTableSeeder

This commands fail on initial install because this tables are not in migrations (except user table, but the seed needs user_role table with is not available)

When I create tables manually everything works ... except that in the admin panel in user part some classes are missing.

**Comment by Renfos** [comment]
Migration files updated
Update user package and try again
