### ISSUE TITLE
Migrate issues

### ISSUE THREAD

**Issue by Qurus** [LavaLite/cms#35]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint faile  
  d: pages.id (SQL: insert into "pages" ("abstract", "banner", "compiler", "c  
  ontent", "description", "heading", "id", "images", "keyword", "name", "orde  
  r", "slug", "status", "title", "view") select  as "abstract",  as "banner",  
    as "compiler", Home Page as "content",  as "description", Home as "headin  
  g", 1 as "id",  as "images",  as "keyword", Home as "name", 0 as "order", h  
  ome as "slug", 1 as "status", Home as "title", page as "view" union all sel  
  ect  as "abstract",  as "banner",  as "compiler", About Us as "content",  a  
  s "description", About Us as "heading", 2 as "id",  as "images",  as "keywo  
  rd", About Us as "name", 0 as "order", about-us as "slug", 1 as "status", A  
  bout Us as "title", page as "view" union all select  as "abstract",  as "ba  
  nner",  as "compiler", <p><br></p> as "content",  as "description", Contact  
   Us as "heading", 3 as "id",  as "images",  as "keyword", Contact Us as "na  
  me", 0 as "order", contact as "slug", 1 as "status", Contact Us as "title",  
   page as "view" union all select  as "abstract",  as "banner",  as "compile  
  r", <p><br></p> as "content",  as "description", Page Not found as "heading  
  ", 4 as "id",  as "images",  as "keyword", Page Not found as "name", 0 as "  
  order", 404 as "slug", 1 as "status", Page Not found as "title", page as "v  
  iew")

**Comment by Renfos** [comment]
Migration files updated
Update user package and try again
