### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by myelin13** [LavaLite/cms#45]
When I installing Lavalite CMS on OSX, first I ran "git clone https://github.com/LavaLite/cms.git" and after that I ran "composer install", but in the end I get this error:

> php artisan clear-compiled

[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Trans' not found

Any help with this ? Thank you.

**Comment by sonoftheweb** [comment]
I get the same error. Any fix to this?

**Comment by Renfos** [comment]
Try installing again
