### ISSUE TITLE
Demo credentials don't work

### ISSUE THREAD

**Issue by kdoichinov** [LavaLite/cms#47]
Hey, I wanted to try out the demo here:
http://demo.lavalite.org/auth/admin/login

However, the admin credentials do not work, I get a message saying "- These credentials do not match our records."
Username: superuser@superuser.com
Password: superuser@superuser

Has this changed?
Thanks!

**Comment by Renfos** [comment]
Credentials updated

**Comment by agaplus** [comment]
you can renew the credentials? i get same message of kdoichinov. Thank you!

**Comment by alvincrisuy** [comment]
still cannot login
