### ISSUE TITLE
page  xx.com/about-us.html

### ISSUE THREAD

**Issue by zanjs** [LavaLite/cms#56]
```
ErrorException in PublicController.php line 35:
Undefined property: Illuminate\Database\Eloquent\Collection::$title
```

![2016-02-26_164749](https://cloud.githubusercontent.com/assets/12947276/13347526/55432ba6-dca9-11e5-8a80-f9b1f256109d.png)

**Comment by Renfos** [comment]
Framework updated.
Run `composer update` again.
