### ISSUE TITLE
Can't get user registration page to work

### ISSUE THREAD

**Issue by javaftper** [LavaLite/cms#65]
I installed lavalite following instructions.

I have the latest version of laravel, lavalite and illuminate.

On the http://localhost:8000/register I have input a valid name, email and password fields but when clicking to sign up the fields are cleared and the user is not added to the database.
No exception error.
![screen](https://cloud.githubusercontent.com/assets/13317379/13822957/9a6235d8-eb9f-11e5-84c1-721b66f7be20.png)

**Comment by Renfos** [comment]
Please update with the new release.
