### ISSUE TITLE
After Login in Demo - Error

### ISSUE THREAD

**Issue by h4hardik** [LavaLite/cms#71]
Hello,

After Login on the demo site, it gives error. "ErrorException in MenuRepository.php line 126:"

**Comment by ergonomicus** [comment]
Same here...

**Comment by csanda87** [comment]
ErrorException in MenuRepository.php line 126:
Trying to get property of non-object (View: /home/lavalite/public_html/demo/public/themes/admin/partials/aside.blade.php) (View: /home/lavalite/public_html/demo/public/themes/admin/partials/aside.blade.php)

**Comment by Renfos** [comment]
Updated the database.
Please check it again.
