### ISSUE TITLE
Trait 'Litepie\User\Traits\RegisterAndLogin' not found

### ISSUE THREAD

**Issue by sangnguyenplus** [LavaLite/cms#77]
![screenshot 36](https://cloud.githubusercontent.com/assets/6972407/14881406/c990b658-0d01-11e6-90b7-7b90ae294914.png)

**Comment by TheLand** [comment]
You have to change in AuthController on the 6th row: 
use Litepie\User\Traits\RegisterAndLogin; to `use Litepie\User\Traits\Auth\RegisterAndLogin;`

**Comment by psc-it** [comment]
composer dump-autoload worked for me
