### ISSUE TITLE
Composer installation has bugs

### ISSUE THREAD

**Issue by TheLand** [LavaLite/cms#79]
I tried the composer installation but i continuosly have bugs like Traits not found or views not found.
Than i tried with the Repository and all seems to work

**Comment by Renfos** [comment]
Run `composer update` again.

**Comment by TheLand** [comment]
I run it, but when I try to go to Login page i'll get this error:
`Trait 'Litepie\User\Traits\RegisterAndLogin' not found` in AuthController.php line 21

**Comment by Renfos** [comment]
Updated all packages. please try it again

**Comment by TheLand** [comment]
Now works! Great job
