### ISSUE TITLE
Demo Admin

### ISSUE THREAD

**Issue by raffaalves** [LavaLite/cms#80]
demo site admin login credentials and register not working

**Comment by franz-josef-kaiser** [comment]
Just had the same problem. Is this project still maintained?

**Comment by georgemjohn** [comment]
You can check it again now.

**Comment by franz-josef-kaiser** [comment]
@georgemjohn Sorry, but it does _not_ work. See the jQuery error (`$` is not a function). I set the `input`s `type` to `text` so you can see the password in the screenshot.

<img width="618" alt="pass" src="https://cloud.githubusercontent.com/assets/387666/19625831/97585282-9923-11e6-87f7-01cc1486b149.png">
<img width="768" alt="type_text" src="https://cloud.githubusercontent.com/assets/387666/19625827/7909b226-9923-11e6-9119-b4c0435a8f00.png">
<img width="763" alt="jquery_error" src="https://cloud.githubusercontent.com/assets/387666/19625828/790b6800-9923-11e6-9664-ff40f1ec8326.png">
